apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: beta
spec:
  serviceName: "beta"
  replicas: 1
  selector:
    matchLabels:
      app: beta
  template:
    metadata:
      labels:
        app: beta
      annotations:
        restartTimestamp: "0"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: main
          image: ubuntu:latest
          command: ["sh", "-c", "touch /tmp/healthy; while true; do sleep 5; done"]
          resources:
            limits:
              memory: "32Mi"
          volumeMounts:
            - name: log
              mountPath: /mnt/log
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "test -f /tmp/healthy"
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "test ! -f /tmp/fail"
            initialDelaySeconds: 2
            periodSeconds: 5
      initContainers:
      - name: init
        image: busybox
        command:
          - sh
          - -c
          - "echo Init beta at $(date) > /mnt/log/init.txt"
        volumeMounts:
        - name: log
          mountPath: /mnt/log
      volumes:
      - name: log
        emptyDir: {}
