apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"sts-restart-watcher","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"sts-restart-watcher"}},"template":{"metadata":{"labels":{"app":"sts-restart-watcher"}},"spec":{"containers":[{"env":[{"name":"WATCH_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"TARGET_STS","value":"alpha,beta"},{"name":"DEBUG","value":"true"},{"name":"SLEEP_SECONDS","value":"10"}],"image":"mkihr1/sts-restart-watcher:sleep","imagePullPolicy":"Always","name":"watcher","resources":{"limits":{"cpu":"200m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"serviceAccountName":"sts-watcher"}}}}
  creationTimestamp: "2025-07-01T10:17:50Z"
  generation: 1
  name: sts-restart-watcher
  namespace: default
  resourceVersion: "2362"
  uid: f2b63d90-0078-439a-8216-3c5216e37f73
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sts-restart-watcher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sts-restart-watcher
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: TARGET_STS
          value: alpha,beta
        - name: DEBUG
          value: "true"
        - name: SLEEP_SECONDS
          value: "60"
        image: mkihr1/watcher:latest
        imagePullPolicy: Always
        name: watcher
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sts-watcher
      serviceAccountName: sts-watcher
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-01T10:17:59Z"
    lastUpdateTime: "2025-07-01T10:17:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-01T10:17:50Z"
    lastUpdateTime: "2025-07-01T10:17:59Z"
    message: ReplicaSet "sts-restart-watcher-597b7cbb8f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
