apiVersion: v1
kind: ServiceAccount
metadata:
  name: sts-watcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sts-watcher-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sts-watcher-bind
  namespace: default
subjects:
- kind: ServiceAccount
  name: sts-watcher
  namespace: default
roleRef:
  kind: Role
  name: sts-watcher-role
  apiGroup: rbac.authorization.k8s.io