apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"alpha","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"alpha"}},"serviceName":"alpha","template":{"metadata":{"annotations":{"restartTimestamp":"0"},"labels":{"app":"alpha"}},"spec":{"containers":[{"command":["sh","-c","tail -f /dev/null"],"image":"busybox:uclibc","name":"main","resources":{"limits":{"memory":"32Mi"}},"volumeMounts":[{"mountPath":"/mnt/log","name":"log"}]}],"initContainers":[{"command":["sh","-c","echo Init alpha at $(date) \u003e /mnt/log/init.txt"],"image":"busybox","name":"init","volumeMounts":[{"mountPath":"/mnt/log","name":"log"}]}],"terminationGracePeriodSeconds":5,"volumes":[{"emptyDir":{},"name":"log"}]}}}}
  creationTimestamp: "2025-07-01T10:18:44Z"
  generation: 2
  name: alpha
  namespace: default
  resourceVersion: "2706"
  uid: 01477e3f-7b4b-4f96-ac23-2cdb31041110
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alpha
  serviceName: alpha
  template:
    metadata:
      annotations:
        restartTimestamp: "0"
      creationTimestamp: null
      labels:
        app: alpha
    spec:
      containers:
      - command:
        - sh
        - -c
        - tail -f /dev/null
        image: debian
        imagePullPolicy: Always
        name: main
        resources:
          limits:
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/log
          name: log
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - echo Init alpha at $(date) > /mnt/log/init.txt
        image: busybox
        imagePullPolicy: Always
        name: init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/log
          name: log
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
      volumes:
      - emptyDir: {}
        name: log
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: alpha-7557786c99
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updateRevision: alpha-7557786c99
  updatedReplicas: 1
