name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: yourdockerhubuser/watcher
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          # Custom tags for push/pull_request
          type=raw,value=ci_latest,enable={{is_pr||is_push}}
          type=raw,value=${{ github.run_id }}-${{ github.run_number }},enable={{is_pr||is_push}}
          # For release
          type=semver,pattern={{version}},enable={{is_release}}
          type=raw,value=latest,enable={{is_release}}
      env:
        is_pr: ${{ github.event_name == 'pull_request' }}
        is_push: ${{ github.event_name == 'push' }}
        is_release: ${{ github.event_name == 'release' }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # Optionally, output the tags
    - name: Show tags
      run: echo "${{ steps.meta.outputs.tags }}"
